from django.urls import path
from users import views

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('profile/', views.profile_view, name='profile'),
    path('profile_edit/', views.profile_edit_view, name='profile_edit'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('api/song/<int:song_id>/', views.get_song_data, name='get_song_data'),
    path('api/song/update/', views.update_song, name='update_song'),
    path('api/song/delete/<int:song_id>/', views.delete_song, name='delete_song'),
    path('api/song/add/', views.add_song, name='add_song'),
    path('dashboard/add_song/', views.admin_add_song_view, name='admin_add_song'),
    path('dashboard/edit_song/', views.admin_edit_song_view, name='admin_edit_song'),
    path('dashboard/edit_song/<int:song_id>/', views.admin_edit_song_detail_view, name='admin_edit_song_detail'),
    path('dashboard/manage_artists/', views.manage_artists_view, name='manage_artists'),
    path('dashboard/add_artist/', views.add_artist_view, name='add_artist'),
    path('dashboard/edit_artist/<int:artist_id>/', views.edit_artist_view, name='edit_artist'),
    path('api/artist/add/', views.add_artist_api, name='add_artist_api'),
    path('api/artist/update/<int:artist_id>/', views.update_artist_api, name='update_artist_api'),
    path('api/artist/delete/<int:artist_id>/', views.delete_artist_api, name='delete_artist_api'),
    path('users/', views.manage_users_view, name='manage_users'),
    path('users/add/', views.add_user_view, name='add_user'),
    path('users/edit/<int:user_id>/', views.edit_user_view, name='edit_user'),
    path('api/user/add/', views.add_user_api, name='add_user_api'),
    path('api/user/update/<int:user_id>/', views.update_user_api, name='update_user_api'),
    path('api/user/delete/<int:user_id>/', views.delete_user_api, name='delete_user_api'),
    path('dashboard/manage_genres/', views.manage_genres_view, name='manage_genres'),
    path('dashboard/add_genre/', views.add_genre_view, name='add_genre'),
    path('dashboard/edit_genre/<int:genre_id>/', views.edit_genre_view, name='edit_genre'),
    path('api/genre/add/', views.add_genre_api, name='add_genre_api'),
    path('api/genre/update/<int:genre_id>/', views.update_genre_api, name='update_genre_api'),
    path('api/genre/delete/<int:genre_id>/', views.delete_genre_api, name='delete_genre_api'),
    path('dashboard/manage_instruments/', views.manage_instruments_view, name='manage_instruments'),
    path('dashboard/add_instrument/', views.add_instrument_view, name='add_instrument'),
    path('dashboard/edit_instrument/<int:instrument_id>/', views.edit_instrument_view, name='edit_instrument'),
    path('api/instrument/add/', views.add_instrument_api, name='add_instrument_api'),
    path('api/instrument/update/<int:instrument_id>/', views.update_instrument_api, name='update_instrument_api'),
    path('api/instrument/delete/<int:instrument_id>/', views.delete_instrument_api, name='delete_instrument_api'),
    path('terms/', views.terms_view, name='terms'),
    path('privacy/', views.privacy_view, name='privacy'),
]