# Generated by Django 5.2.4 on 2025-08-13 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-music', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('strings', 'Strings'), ('percussion', 'Percussion'), ('wind', 'Wind'), ('keyboard', 'Keyboard'), ('electronic', 'Electronic')], max_length=50)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='fas fa-music', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('genres', models.ManyToManyField(to='content.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('key', models.CharField(max_length=20)),
                ('bpm', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='song_covers/')),
                ('audio_file', models.FileField(upload_to='song_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.artist')),
                ('genres', models.ManyToManyField(to='content.genre')),
            ],
        ),
        migrations.CreateModel(
            name='LyricsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('verse', 'Verse'), ('chorus', 'Chorus'), ('bridge', 'Bridge'), ('intro', 'Intro'), ('outro', 'Outro')], max_length=20)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='content.song')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChordProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord_name', models.CharField(max_length=20)),
                ('chord_type', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chords', to='content.song')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SongInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.instrument')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.song')),
            ],
            options={
                'unique_together': {('song', 'instrument')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='instruments',
            field=models.ManyToManyField(through='content.SongInstrument', to='content.instrument'),
        ),
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.instrument')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='content.song')),
            ],
        ),
    ]
