# Generated by Django 5.2.4 on 2025-08-15 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='song',
            name='saved_by',
            field=models.ManyToManyField(related_name='saved_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
